services:
  web:
    # build: .
    #image: dairoot/xiaozhi-webrtc:latest
    image: xiaozhi-webrtc:latest
    ports:
      - "${PORT:-51000}:${PORT:-51000}"
    volumes:
      - ./:/app/
    network_mode: "host"
    environment:
      - PORT=51000
      - ICE_MASTER_KEY=9fcotuB_ntxL4EIRMxHk2a4S9zs5fOviL80IYrXLnq4=
      - CLOUDFLARE_TURN_USERNAME=encrypted:Z0FBQUFBQm9fZ2k0Mk9kUHpUbkpiTDNlQTVTeFpEVmpydC1zVTBzOWxKUUdGSlY5aE1pM3JIenpudEFpWV9WN2R3VFVpVmpBWGNjZVp1N3pJVnJHNzFydVZkRXhPTDBFRmNfSTJ5TkFSWjhURHczMkZXLTNZekd4VDhCLXVWYmlTcTRkZlpBQ2VIMkc=
      - CLOUDFLARE_TURN_CREDENTIAL=encrypted:Z0FBQUFBQm9fZ2k0Y0ZPVG8xd3MxTndTZlVxZGZldEhIRHN6V1ZWWDRDaUVHYWFMcmtlQzNWLXp0WjZ4UkxWY28wZ0NCR3RDaEl0cXFBQmR0MnhYalVkS2NPdHV5UjJuWmtLWVhESmRzWTBfa2VSd2RoTW5vdV9MN00tdWtFSTRJNGYyYmY5bVp4M2ZhbklIOEk4RkNyV2dSZnZvd3ZNVGtrYmlRZ2dIWXZtRDVGY3YtS2dsdk5VPQ==
      - TURN_SERVER_COUNT=1
      - TURN_SERVER_1_URLS=turn:turn.cloudflare.com:3478?transport=udp,turn:turn.cloudflare.com:3478?transport=tcp,turns:turn.cloudflare.com:5349?transport=tcp
      - TURN_SERVER_1_USERNAME=encrypted:Z0FBQUFBQm9fZ2k0Mk9kUHpUbkpiTDNlQTVTeFpEVmpydC1zVTBzOWxKUUdGSlY5aE1pM3JIenpudEFpWV9WN2R3VFVpVmpBWGNjZVp1N3pJVnJHNzFydVZkRXhPTDBFRmNfSTJ5TkFSWjhURHczMkZXLTNZekd4VDhCLXVWYmlTcTRkZlpBQ2VIMkc=
      - TURN_SERVER_1_CREDENTIAL=encrypted:Z0FBQUFBQm9fZ2k0Y0ZPVG8xd3MxTndTZlVxZGZldEhIRHN6V1ZWWDRDaUVHYWFMcmtlQzNWLXp0WjZ4UkxWY28wZ0NCR3RDaEl0cXFBQmR0MnhYalVkS2NPdHV5UjJuWmtLWVhESmRzWTBfa2VSd2RoTW5vdV9MN00tdWtFSTRJNGYyYmY5bVp4M2ZhbklIOEk4RkNyV2dSZnZvd3ZNVGtrYmlRZ2dIWXZtRDVGY3YtS2dsdk5VPQ==
